version: '3.7'

services:

  snmp_exporter:
    image: thinkhu/snmp_exporter:v1
    volumes:
      - type: bind
        source: ./snmp_exporter/snmp.yml
        target: /snmp.yml
        read_only: true
    ports:
      - "9116:9116"
    networks:
      - prom
    
  prometheus:
    depends_on:
      - snmp_exporter
    image: prom/prometheus:latest
    volumes:
      - type: bind
        source: ./prometheus/prometheus.yml
        target: /etc/prometheus/prometheus.yml
        read_only: true
      - type: volume
        source: prometheus
        target: /prometheus
    ports:
      - "9090:9090"
    networks:
      - prom

  grafana:
    depends_on:
      - prometheus
    image: grafana/grafana:latest
    volumes:
      - type: volume
        source: grafana
        target: /var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - prom

volumes:
  prometheus:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./prometheus/data
  grafana:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./grafana
      
networks:
  prom:
    driver: bridge